## Variables
A box for storing data

In [ ]:
# perform operations
a = 10
b = 20
a+b

30

In [ ]:
# store strings
c = "Hello world"
d = " Have a great day"
c + d

'Hello world Have a great day'

In [ ]:
# different variable types
a + c

TypeError: ignored

## Lists

A box for storing multiple data


In [ ]:
# creating a list
e = [1,2,3,4]
e

[1, 2, 3, 4]

In [ ]:
# accessing items in a list
e[0]

1

In [ ]:
# nested lists
f = [[1,2,3], "Hello", 2021]
f[1]

'Hello'

In [ ]:
# length of the list
len(f)

3

## Arrays

Similar to a list, but for data science


In [ ]:
#library for arrays
import numpy as np

In [ ]:
# 1D array 
g = [1,2,3,4]
np.array(g)

array([1, 2, 3, 4])

In [ ]:
# 2D array
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# random array
h = np.random.randint(-100, 100, (3,3))
h

array([[ 31, -17, -59],
       [-55,  70,  21],
       [ 90,  65, -85]])

In [ ]:
# shape of the array
h.shape

(3, 3)

In [ ]:
# data type in the array
h.dtype

dtype('float64')

## Dataframes

Tables of data

In [ ]:
# library for dataframes
import pandas as pd

In [ ]:
rows= ['A', 'B', 'C', 'D', 'E'] # row labels
columns= ['W', 'X', 'Y', 'Z'] # column labels

In [ ]:
# create an array
data = np.random.randint(-100,100,(5,4))
data

array([[  61,  -52, -100,  -67],
       [ -74,   62,  -30,   83],
       [  42,   18,  -45,   18],
       [-100,   46,   -3,   54],
       [ -86,   78,   94,  -97]])

In [ ]:
# convert array to table
df = pd.DataFrame(data,rows,columns)
df

W   X    Y   Z
A   61 -52 -100 -67
B  -74  62  -30  83
C   42  18  -45  18
D -100  46   -3  54
E  -86  78   94 -97

In [ ]:
#add a new column
df['new'] = df['W'] + df['Y']
df

W   X    Y   Z  new
A   61 -52 -100 -67  -39
B  -74  62  -30  83 -104
C   42  18  -45  18   -3
D -100  46   -3  54 -103
E  -86  78   94 -97    8

## If Statements

Comparing stuff

In [36]:
x,y = 1,2

if x > y:
  print("x is greater than y")
elif x < y:
  print("x is less than y")
else:
  print("x is equal to y")

x is less than y


In [27]:
#To umbrella or not to umbrella
raining = False
if raining == True:
  print("Take an umbrella")
else:
  print("No umbrella needed")

No umbrella needed


In [29]:
#another way
if raining:
  print("Take an umbrella")
else:
  print("No umbrella needed")

No umbrella needed


## Functions

Recyclable code

In [21]:
#simple example
def addTwoItems(x,y):
  sum = x+y
  return sum

In [20]:
addTwoItems(4,5)

9

In [24]:
addTwoItems("Kevin"," is hardstuck gold")

'Kevin is hardstuck gold'

In [98]:
your_score = 0
computer_score=0

In [115]:
#advanced example
import random

def RPS():
  global your_score
  global computer_score

  #player choices
  user_input = input("Enter a choice (rock, paper, scissors): ")
  options = ["rock", "paper", "scissors"]
  computer_input = random.choice(options)

  print(f"\nYou chose {user_input}, computer chose {computer_input}.\n")

  #dealing with ties
  if user_input == computer_input:
    print(f"Both players selected {user_input}. It's a tie!")

  #if you pick rock
  elif user_input == "rock":
    if computer_input == "scissors":
      print("Rock smashes scissors! You win!")
      your_score += 1
    else:
      print("Paper covers rock! You lose.")
      computer_score +=1

  #if you pick paper
  elif user_input == "paper":
    if computer_input == "rock":
      print("Paper covers rock! You win!")
      your_score += 1
    else:
      print("Scissors cuts paper! You lose.")
      computer_score +=1

  #if you pick scissors
  elif user_input == "scissors":
    if computer_input == "paper":
      print("Scissors cuts paper! You win!")
      your_score += 1
    else:
      print("Rock smashes scissors! You lose.")
      computer_score +=1
  
  #keep score
  print(f"\nYou:{your_score} \nComputer:{computer_score}")

In [116]:
RPS()

Enter a choice (rock, paper, scissors): rock

You chose rock, computer chose paper.

Paper covers rock! You lose.

You:5 
Computer:2
